### ISSUE TITLE
"Spoofing is not possible" when it actually is

### ISSUE THREAD

**Issue by rloretan** [MattKeeley/Spoofy#28]
Hi,

Thanks for the tool, it's great!

I believe I found a bug. The following SPF record encountered during a security assessment was indeed spoofable:

```
[*] Domain: xxx.com
[*] Is subdomain: False
[*] DNS Server: 1.1.1.1
[*] SPF record: v=spf1 mx exists:%{i}.spf.zzz.iphmx.com include:spf.protection.outlook.com
[*] SPF does not contain an "All" item.
[*] SPF DNS query count: 3
[?] No DMARC record found.
[-] Spoofing is not possible for xxx.com.
```

From my understanding the reason it's spoofable is simply the missing "All" item in combination with no DMARC. In the mail headers of my spoofed mail I could see

Authentication-Results: spf=neutral (sender IP is y.y.y.y) smtp.mailfrom=xxx.com; dkim=none (message not signed) header.d=none;dmarc=none action=none header.from=xxx.com;compauth=none reason=405
Received-SPF: Neutral (protection.outlook.com: y.y.y.y is neither permitted nor denied by domain of xxx.com)

Or am I missing something / is this behavior intended?

**Comment by MattKeeley** [comment]
Moving to #29. Will be updating the logic table to reflect the new outlook changes. Thanks for opening this issue!
