### ISSUE TITLE
Multipart domain

### ISSUE THREAD

**Issue by brianberryNZ** [MattKeeley/Spoofy#6]
I live in New Zealand where we have multipart domain names e.g. mydomain.co.nz. This kind of domain fails in the get_dmarc_record and get_dmarc_org_policy functions.
If I do something like:
_def get_dmarc_record(domain):
    if domain.endswith(".com") & domain.count('.') > 1: return get_dmarc_org_policy(domain)_
or
_def get_dmarc_record(domain):
    if domain.find(".co.") < 1 & domain.count('.') > 1: return get_dmarc_org_policy(domain)_
Then my domains work. The complication is that you have heaps of other top-level domains now, so using just ".com" isn't a solution:
.biz
.kiwi
.co
Also, there are a few places similar to Australia who use mydomain.com.au which will also cause issues.
I'm not good enough with Python to offer a robust solution for this, but I'm sure there is a way.

**Comment by MattKeeley** [comment]
Should be fixed now. Introducing a new import to specifically look at top level domains for all domains.
