### ISSUE TITLE
Parsing TXT Records incorrectly

### ISSUE THREAD

**Issue by l4rRyxz** [MattKeeley/Spoofy#8]
### Description

If a TXT record is resolved with greater than 256 characters. The script replaces the " to concatenate the second TXT record.
Example if something like this appears "-al" "l" in seperated TXT records because of length the script does not recognize the setting, as it parses it from -al" "l" to -al l". This can be quickly fixed, we see this error with our own company domain. 

I don't want to put in our explicit example from the logs, to not expose any details here on github.
I fixed this already in my local cloned version of you script, however I would like to address this as it may create false-positives for others.

#### Current Code

```
                spf_record = str(dns_data).replace('"','')
```

#### Code Change

```
                spf_record = str(dns_data).replace('" "','')

```

This will handle the concatenation correctly and makes "-al l" to "-all" and also of course any other strings that are split on the TXT size limit. :)

**Comment by MattKeeley** [comment]
Fixed in most recent commit. I couldnt recreate the bug with the length over 256 but the alls are now parsing with optional spaces in the regex.
